import { CommunitySeed } from './types';

export const communities: CommunitySeed[] = [
  {
    key: 'community-innovadores',
    name: 'Innovadores Caracas',
    description: 'Club de founders, developers y product managers enfocados en soluciones urbanas.',
    image: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7',
    createdByKey: 'admin-juan',
    categoryKey: 'category-tecnologia',
  },
  {
    key: 'community-foodies',
    name: 'Foodies de Sabores Caraquenos',
    description: 'Exploradores de la gastronomia local con rutas semanales por mercados y restaurantes.',
    image: 'https://images.unsplash.com/photo-1473093226795-af9932fe5856',
    createdByKey: 'market-sofia',
    categoryKey: 'category-gastronomia',
  },
  {
    key: 'community-nightowls',
    name: 'Night Owls Caracas',
    description: 'Entusiastas de la vida nocturna con focus en experiencias premium y seguridad.',
    image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf',
    createdByKey: 'market-alejandro',
    categoryKey: 'category-musica',
  },
  {
    key: 'community-waraira',
    name: 'Waraira Active',
    description: 'Grupo de entrenamientos y bienestar que aman el Avila y el aire libre.',
    image: 'https://images.unsplash.com/photo-1526401485004-46910ecc8e51',
    createdByKey: 'client-gabriel',
    categoryKey: 'category-deportes',
  },
  {
    key: 'community-runners-altamira',
    name: 'Runners Altamira',
    description: 'Equipo de running con salidas al amanecer por Altamira y Bello Monte.',
    image: 'https://images.unsplash.com/photo-1517964106626-460c5db4215c',
    createdByKey: 'client-sergio',
    categoryKey: 'category-deportes',
  },
  {
    key: 'community-padel-mercedes',
    name: 'Padel Las Mercedes',
    description: 'Jugadores intermedios y avanzados organizando ladders y torneos express.',
    image: 'https://images.unsplash.com/photo-1601132359864-42e45f5a0f90',
    createdByKey: 'client-ricardo',
    categoryKey: 'category-deportes',
  },
  {
    key: 'community-tenis-avila',
    name: 'Tenis Avila Club',
    description: 'Comunidad de tennis en Caracas con clinics tecnicos y encuentros sociales.',
    image: 'https://images.unsplash.com/photo-1542145937-2ef824490b6b',
    createdByKey: 'client-daniela',
    categoryKey: 'category-deportes',
  },
  {
    key: 'community-senderistas',
    name: 'Senderistas Caraquenos',
    description: 'Amantes del trekking urbano y rutas eco turisticas en el Waraira Repano.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
    createdByKey: 'client-luisa',
    categoryKey: 'category-sostenibilidad',
  },
  {
    key: 'community-jazz-lounge',
    name: 'Jazz Lounge Caracas',
    description: 'Coleccionistas y musicos de jazz que organizan listening sessions exclusivas.',
    image: 'https://images.unsplash.com/photo-1507835661228-31c3691633c4',
    createdByKey: 'client-juan-andres-cuevas',
    categoryKey: 'category-musica',
  },
  {
    key: 'community-house-underground',
    name: 'House Underground CCS',
    description: 'DJ y productores de house que impulsan fiestas boutique y talleres de produccion.',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b',
    createdByKey: 'market-alejandro',
    categoryKey: 'category-musica',
  },
  {
    key: 'community-musica-llanera',
    name: 'Sabana Llanera Caracas',
    description: 'Encuentros de musica llanera, talleres de cuatro y degustaciones gastronomicas.',
    image: 'https://images.unsplash.com/photo-1582719478250-891e0eb60410',
    createdByKey: 'client-mikele-salomon',
    categoryKey: 'category-musica',
  },
  {
    key: 'community-cine-forum',
    name: 'Cine Club Metropolitano',
    description: 'Cinefilos que organizan cine foros de peliculas independientes y clasicas.',
    image: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c',
    createdByKey: 'client-elisabeth',
    categoryKey: 'category-peliculas',
  },
];
