import { EventVisibility } from '@prisma/client';

import { EventSeed } from './types';

export const events: EventSeed[] = [
    {
        key: 'event-dev-meetup',
        name: 'Dev Meetup Caracas: Product Builders',
        description: 'Charlas lightning sobre product discovery y escalamiento de startups caraquenas.',
        timeBegin: new Date('2025-02-12T18:30:00-04:00'),
        timeEnd: new Date('2025-02-12T21:30:00-04:00'),
        placeKey: 'place-altamira-hub',
        organizerKey: 'admin-juan',
        communityKey: 'community-innovadores',
        categoryKey: 'category-tecnologia',
        minAge: 18,
        status: 'proximo',
        visibility: EventVisibility.PUBLIC,
        externalUrl: 'https://lu.ma/devmeetupccs',
        image: 'https://images.unsplash.com/photo-1518770660439-4636190af475',
    },
    {
        key: 'event-ruta-gastronomica',
        name: 'Ruta Gastronomica Sabores del Bolivar',
        description: 'Recorrido guiado por puestos iconicos de arepas, jugos y postres en el Mercado de Chacao.',
        timeBegin: new Date('2025-03-02T10:00:00-04:00'),
        timeEnd: new Date('2025-03-02T14:30:00-04:00'),
        placeKey: 'place-mercado-mercedes',
        organizerKey: 'market-sofia',
        communityKey: 'community-foodies',
        categoryKey: 'category-gastronomia',
        minAge: 12,
        status: 'proximo',
        visibility: EventVisibility.PUBLIC,
        image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f',
    },
    {
        key: 'event-rooftop-electronica',
        name: 'Nocturna 360 Sunset Electronico',
        description: 'Lineup de DJs venezolanos con visuales inmersivos y barra de cocteles de autor.',
        timeBegin: new Date('2025-02-28T20:00:00-04:00'),
        timeEnd: new Date('2025-03-01T02:30:00-04:00'),
        placeKey: 'place-nocturna-360',
        organizerKey: 'market-alejandro',
        communityKey: 'community-nightowls',
        categoryKey: 'category-musica',
        minAge: 21,
        status: 'proximo',
        visibility: EventVisibility.PRIVATE,
        externalUrl: 'https://ticketplate.com/nocturna360',
        image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819',
    },
    {
        key: 'event-teresa-sinf',
        name: 'Gala Sinfonica Teresa Carreno',
        description: 'Programa especial con repertorio de compositores venezolanos contemporaneos.',
        timeBegin: new Date('2025-03-18T19:00:00-04:00'),
        timeEnd: new Date('2025-03-18T21:15:00-04:00'),
        placeKey: 'place-teresa-carreno',
        organizerKey: 'admin-juan',
        categoryKey: 'category-arte',
        minAge: 10,
        status: 'proximo',
        visibility: EventVisibility.PUBLIC,
        image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
    },
    {
        key: 'event-waraira-sunrise',
        name: 'Sunrise Training Waraira Fit',
        description: 'Entrenamiento funcional grupal con respiracion guiada frente al amanecer del Avila.',
        timeBegin: new Date('2025-02-09T06:00:00-04:00'),
        timeEnd: new Date('2025-02-09T08:00:00-04:00'),
        placeKey: 'place-waraira-fit',
        organizerKey: 'client-gabriel',
        communityKey: 'community-waraira',
        categoryKey: 'category-salud-bienestar',
        minAge: 16,
        status: 'proximo',
        visibility: EventVisibility.PUBLIC,
        image: 'https://images.unsplash.com/photo-1439396087961-98bc12c21176',
    },
    {
        key: 'event-podcast-makers',
        name: 'Podcast Makers Lab',
        description: 'Workshop practico para crear pilotos de podcast sobre historias urbanas caraquenas.',
        timeBegin: new Date('2025-03-10T15:00:00-04:00'),
        timeEnd: new Date('2025-03-10T19:00:00-04:00'),
        placeKey: 'place-santa-rosalia-lab',
        organizerKey: 'admin-juan',
        categoryKey: 'category-educacion',
        minAge: 18,
        status: 'proximo',
        visibility: EventVisibility.PRIVATE,
        image: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
    },
];
