import { Status } from '@prisma/client';

import { PlaceSeed } from './types';

export const places: PlaceSeed[] = [
    {
        key: 'place-mercado-mercedes',
        ownerKey: 'market-sofia',
        name: 'Mercado Urbano Las Mercedes',
        direction: 'Avenida Principal de Las Mercedes con Calle Paris',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 220,
        type: 'Food Hall Gastronomico',
        status: Status.ACCEPTED,
        description: 'Food hall con propuestas de cocina fusions criolla y espacios para pop-ups.',
        image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
        mapUrl: 'https://maps.google.com/?q=Las+Mercedes+Caracas',
        igUrl: 'https://instagram.com/mercadourbanolv',
        facebookUrl: 'https://facebook.com/mercadourbanolv',
    },
    {
        key: 'place-altamira-hub',
        ownerKey: 'market-sofia',
        name: 'Altamira Innovation Hub',
        direction: 'Torre Altamira, Avenida Luis Roche',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 180,
        type: 'Espacio Coworking',
        status: Status.ACCEPTED,
        description: 'Coworking con salones para meetups y rooftop con vista al Avila.',
        image: 'https://images.unsplash.com/photo-1483478550801-ceba5fe50e8e',
        mapUrl: 'https://maps.google.com/?q=Altamira+Caracas',
        igUrl: 'https://instagram.com/altamirahub',
    },
    {
        key: 'place-nocturna-360',
        ownerKey: 'market-alejandro',
        name: 'Nocturna 360 Rooftop',
        direction: 'Centro Comercial Tolon, terraza principal',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 450,
        type: 'Rooftop Club Nocturno',
        status: Status.ACCEPTED,
        description: 'Rooftop con sonido envolvente y barra mixologia inspirada en sabores venezolanos.',
        image: 'https://images.unsplash.com/photo-1565299752279-0b407c0b6e9a',
        mapUrl: 'https://maps.google.com/?q=Tolon+Fashion+Mall',
        igUrl: 'https://instagram.com/nocturna360',
        facebookUrl: 'https://facebook.com/nocturna360',
        tiktokUrl: 'https://tiktok.com/@nocturna360',
    },
    {
        key: 'place-teresa-carreno',
        ownerKey: 'admin-juan',
        name: 'Complejo Cultural Teresa Carreno',
        direction: 'Paseo Colon y Avenida Mexico, Los Caobos',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 1200,
        type: 'Teatro Cultural',
        status: Status.ACCEPTED,
        description: 'Sala de conciertos iconica con agenda de teatro, danza y sinfonico.',
        image: 'https://images.unsplash.com/photo-1503095396549-807759245b35',
        mapUrl: 'https://maps.google.com/?q=Teresa+Carreno',
    },
    {
        key: 'place-cafe-chacao',
        ownerKey: 'market-sofia',
        name: 'Cafe Mirador Chacao',
        direction: 'Plaza Francia, nivel Mirador',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 90,
        type: 'Cafeteria de Especialidad',
        status: Status.ACCEPTED,
        description: 'Cafe con tostadora propia y espacios para charlas de emprendimiento local.',
        image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
        mapUrl: 'https://maps.google.com/?q=Plaza+Francia+Caracas',
        igUrl: 'https://instagram.com/cafemiradorchacao',
    },
    {
        key: 'place-waraira-fit',
        ownerKey: 'market-alejandro',
        name: 'Waraira Fit Camp',
        direction: 'Entrada Sabas Nieves, Parque Nacional Waraira Repano',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 300,
        type: 'Zona Outdoor Deportiva',
        status: Status.ACCEPTED,
        description: 'Zona de entrenamiento funcional al aire libre con guias certificados.',
        image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
        mapUrl: 'https://maps.google.com/?q=Sabas+Nieves+Caracas',
    },
    {
        key: 'place-santa-rosalia-lab',
        ownerKey: 'admin-juan',
        name: 'Laboratorio Creativo Santa Rosalia',
        direction: 'Quinta Creativa, Avenida Sur 3, Santa Rosalia',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 140,
        type: 'Estudio Multimedia Creativo',
        status: Status.PENDING,
        description: 'Estudio para produccion audiovisual, talleres de podcast y fotografia.',
        image: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
        mapUrl: 'https://maps.google.com/?q=Santa+Rosalia+Caracas',
    },
    {
        key: 'place-centro-cultural-chacao',
        ownerKey: 'admin-juan',
        name: 'Centro Cultural Chacao',
        direction: 'Avenida Tamanaco, El Rosal, Chacao',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 650,
        type: 'Centro Cultural Urbano',
        status: Status.ACCEPTED,
        description: 'Salas para conciertos, teatro y ferias de emprendimiento en pleno Chacao.',
        image: 'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e',
        mapUrl: 'https://maps.google.com/?q=Centro+Cultural+Chacao',
        igUrl: 'https://instagram.com/cculturalchacao',
    },
    {
        key: 'place-hotel-humboldt',
        ownerKey: 'market-alejandro',
        name: 'Hotel Humboldt Salas Panoramicas',
        direction: 'Cima del Cerro El Avila, Parque Nacional Waraira Repano',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 400,
        type: 'Salon Hotelero Panoramico',
        status: Status.ACCEPTED,
        description: 'Salon panoramico icnico con vista 360 a Caracas para galas y lanzamientos.',
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c',
        mapUrl: 'https://maps.google.com/?q=Hotel+Humboldt',
        igUrl: 'https://instagram.com/hotelhumboldtccs',
    },
    {
        key: 'place-trasnocho-cultural',
        ownerKey: 'market-sofia',
        name: 'Trasnocho Cultural',
        direction: 'Centro Comercial Paseo Las Mercedes, Nivel Trasnocho',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 520,
        type: 'Complejo de Arte Independiente',
        status: Status.ACCEPTED,
        description: 'Complejo con teatros, cine arte y salas para conversatorios y festivales.',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        mapUrl: 'https://maps.google.com/?q=Trasnocho+Cultural',
        igUrl: 'https://instagram.com/trasnochocultural',
    },
    {
        key: 'place-quinta-bar',
        ownerKey: 'market-alejandro',
        name: 'Quinta Bar',
        direction: 'Av. Francisco de Miranda con 3ra Avenida, Los Palos Grandes',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 320,
        type: 'Bar de Musica en Vivo',
        status: Status.ACCEPTED,
        description: 'Spot de cocteleria y conciertos intimos con agenda semanal de bandas locales.',
        image: 'https://images.unsplash.com/photo-1514361895825-84b4bd4d8445',
        mapUrl: 'https://maps.google.com/?q=Quinta+Bar+Caracas',
        igUrl: 'https://instagram.com/quintabar',
    },
    {
        key: 'place-sambil-dome',
        ownerKey: 'admin-juan',
        name: 'Sambil Caracas Dome',
        direction: 'Av. Libertador, Nivel Diversion, Sambil Caracas',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 1500,
        type: 'Escenario en Centro Comercial',
        status: Status.ACCEPTED,
        description: 'Escenario central del Sambil con pasarelas modulares para ferias y conciertos.',
        image: 'https://images.unsplash.com/photo-1503389152951-9f343605f61e',
        mapUrl: 'https://maps.google.com/?q=Sambil+Caracas',
        facebookUrl: 'https://facebook.com/sambilcaracas',
    },
    {
        key: 'place-museo-contemporaneo',
        ownerKey: 'admin-juan',
        name: 'Museo de Arte Contemporaneo de Caracas',
        direction: 'Parque Central, Nivel Bolivar, El Conde',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 900,
        type: 'Museo Moderno',
        status: Status.ACCEPTED,
        description: 'Museo iconico con salas de exposicion, auditorios y espacios educativos.',
        image: 'https://images.unsplash.com/photo-1526498460520-4c246339dccb',
        mapUrl: 'https://maps.google.com/?q=Museo+de+Arte+Contemporaneo+Caracas',
    },
    {
        key: 'place-poliedro-caracas',
        ownerKey: 'admin-juan',
        name: 'Poliedro de Caracas',
        direction: 'Autopista Valle-Coche, La Rinconada',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 13000,
        type: 'Arena Multiproposito',
        status: Status.ACCEPTED,
        description: 'La cupula multiproposito mas grande de la ciudad para conciertos y exposiciones.',
        image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30',
        mapUrl: 'https://maps.google.com/?q=Poliedro+de+Caracas',
    },
    {
        key: 'place-plaza-francia',
        ownerKey: 'client-luisa',
        name: 'Plaza Francia de Altamira',
        direction: 'Av. Francisco de Miranda, Altamira, Chacao',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 500,
        type: 'Plaza Publica',
        status: Status.ACCEPTED,
        description: 'Plaza iconica para ferias, mercados creativos y encuentros culturales.',
        image: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e',
        mapUrl: 'https://maps.google.com/?q=Plaza+Francia+Altamira',
    },
    {
        key: 'place-el-hatillo-casco',
        ownerKey: 'client-elisabeth',
        name: 'Casco Historico El Hatillo',
        direction: 'Plaza Bolivar, Calle Sucre, El Hatillo',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 350,
        type: 'Zona Patrimonial',
        status: Status.ACCEPTED,
        description: 'Zona colonial con casas coloniales, plazas y espacios para festivales de calle.',
        image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef',
        mapUrl: 'https://maps.google.com/?q=El+Hatillo+Caracas',
    },
    {
        key: 'place-alto-restaurant',
        ownerKey: 'market-sofia',
        name: 'Restaurante Alto',
        direction: '3ra Avenida con 5ta Transversal, Los Palos Grandes',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 120,
        type: 'Restaurante de Autor',
        status: Status.ACCEPTED,
        description: 'Restaurante fine dining del chef Carlos Garcia con sala privada para maridajes.',
        image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe',
        mapUrl: 'https://maps.google.com/?q=Restaurante+Alto+Caracas',
        igUrl: 'https://instagram.com/altorest',
    },
    {
        key: 'place-padel-zone',
        ownerKey: 'client-jhonaiker-blanco',
        name: 'Padel Zone Las Mercedes',
        direction: 'Calle Madrid con Avenida Principal, Las Mercedes',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 110,
        type: 'Club de Padel',
        status: Status.ACCEPTED,
        description: 'Centro de padel indoor con canchas profesionales y lounge para jugadores.',
        image: 'https://images.unsplash.com/photo-1604908177093-7886a538c953',
        mapUrl: 'https://maps.google.com/?q=Padel+Las+Mercedes',
    },
    {
        key: 'place-boulevard-sabino',
        ownerKey: 'client-natalia',
        name: 'Boulevard de Sabana Grande',
        direction: 'Tramo Plaza Venezuela hasta Chacaito',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 800,
        type: 'Boulevard Urbano',
        status: Status.ACCEPTED,
        description: 'Corredor peatonal con comercio, arte urbano y funciones itinerantes.',
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c',
        mapUrl: 'https://maps.google.com/?q=Sabana+Grande+Caracas',
    },
    {
        key: 'place-galeria-tolmo',
        ownerKey: 'client-juan-andres-cuevas',
        name: 'Galeria Tolmo',
        direction: 'Avenida Orinoco, Torre La Noria, Las Mercedes',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 200,
        type: 'Galeria de Arte',
        status: Status.ACCEPTED,
        description: 'Galeria boutique dedicada a artistas emergentes venezolanos.',
        image: 'https://images.unsplash.com/photo-1527153907022-465ee4752fdc',
        mapUrl: 'https://maps.google.com/?q=Galeria+Tolmo+Caracas',
    },
    {
        key: 'place-mirador-humboldt',
        ownerKey: 'client-miguel-salomon',
        name: 'Mirador de La Julia',
        direction: 'Via hacia Galipan, sector La Julia',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 180,
        type: 'Mirador de Montana',
        status: Status.ACCEPTED,
        description: 'Mirador de montaña con kioskos y espacios para experiencias de bienestar.',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        mapUrl: 'https://maps.google.com/?q=Mirador+La+Julia+Galipan',
    },
    {
        key: 'place-parque-los-caobos',
        ownerKey: 'client-sergio',
        name: 'Parque Los Caobos',
        direction: 'Avenida Este 2 con Sur 21, Los Caobos',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 1200,
        type: 'Parque Urbano',
        status: Status.ACCEPTED,
        description: 'Parque historico con fuentes, esculturas y explanadas para festivales al aire libre.',
        image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef',
        mapUrl: 'https://maps.google.com/?q=Parque+Los+Caobos',
    },
    {
        key: 'place-parque-del-este',
        ownerKey: 'client-gabriel',
        name: 'Parque del Este - Concha Acustica',
        direction: 'Av. Francisco de Miranda, entrada Parque del Este',
        city: 'Caracas',
        country: 'Venezuela',
        capacity: 1000,
        type: 'Concha Acustica',
        status: Status.ACCEPTED,
        description: 'Concha acustica rodeada de vegetacion ideal para festivales wellness y musica.',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        mapUrl: 'https://maps.google.com/?q=Parque+del+Este+Caracas',
    },
];
