import { Status } from '@prisma/client';

import { PlaceSeed } from './types';

export const places: PlaceSeed[] = [
  {
    key: 'place-mercado-mercedes',
    ownerKey: 'market-sofia',
    name: 'Mercado Urbano Las Mercedes',
    direction: 'Avenida Principal de Las Mercedes con Calle Paris',
    city: 'Caracas',
    country: 'Venezuela',
    capacity: 220,
    type: 'food-hall',
    status: Status.ACCEPTED,
    description: 'Food hall con propuestas de cocina fusions criolla y espacios para pop-ups.',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
    mapUrl: 'https://maps.google.com/?q=Las+Mercedes+Caracas',
    igUrl: 'https://instagram.com/mercadourbanolv',
    facebookUrl: 'https://facebook.com/mercadourbanolv',
  },
  {
    key: 'place-altamira-hub',
    ownerKey: 'market-sofia',
    name: 'Altamira Innovation Hub',
    direction: 'Torre Altamira, Avenida Luis Roche',
    city: 'Caracas',
    country: 'Venezuela',
    capacity: 180,
    type: 'coworking',
    status: Status.ACCEPTED,
    description: 'Coworking con salones para meetups y rooftop con vista al Avila.',
    image: 'https://images.unsplash.com/photo-1483478550801-ceba5fe50e8e',
    mapUrl: 'https://maps.google.com/?q=Altamira+Caracas',
    igUrl: 'https://instagram.com/altamirahub',
  },
  {
    key: 'place-nocturna-360',
    ownerKey: 'market-alejandro',
    name: 'Nocturna 360 Rooftop',
    direction: 'Centro Comercial Tolon, terraza principal',
    city: 'Caracas',
    country: 'Venezuela',
    capacity: 450,
    type: 'rooftop-club',
    status: Status.ACCEPTED,
    description: 'Rooftop con sonido envolvente y barra mixologia inspirada en sabores venezolanos.',
    image: 'https://images.unsplash.com/photo-1565299752279-0b407c0b6e9a',
    mapUrl: 'https://maps.google.com/?q=Tolon+Fashion+Mall',
    igUrl: 'https://instagram.com/nocturna360',
    facebookUrl: 'https://facebook.com/nocturna360',
    tiktokUrl: 'https://tiktok.com/@nocturna360',
  },
  {
    key: 'place-teresa-carreno',
    ownerKey: 'admin-juan',
    name: 'Complejo Cultural Teresa Carreno',
  direction: 'Paseo Colon y Avenida Mexico, Los Caobos',
    city: 'Caracas',
    country: 'Venezuela',
    capacity: 1200,
    type: 'theater',
    status: Status.ACCEPTED,
    description: 'Sala de conciertos iconica con agenda de teatro, danza y sinfonico.',
    image: 'https://images.unsplash.com/photo-1503095396549-807759245b35',
    mapUrl: 'https://maps.google.com/?q=Teresa+Carreno',
  },
  {
    key: 'place-cafe-chacao',
    ownerKey: 'market-sofia',
    name: 'Cafe Mirador Chacao',
    direction: 'Plaza Francia, nivel Mirador',
    city: 'Caracas',
    country: 'Venezuela',
    capacity: 90,
    type: 'cafe',
    status: Status.ACCEPTED,
    description: 'Cafe con tostadora propia y espacios para charlas de emprendimiento local.',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
    mapUrl: 'https://maps.google.com/?q=Plaza+Francia+Caracas',
    igUrl: 'https://instagram.com/cafemiradorchacao',
  },
  {
    key: 'place-waraira-fit',
    ownerKey: 'market-alejandro',
    name: 'Waraira Fit Camp',
    direction: 'Entrada Sabas Nieves, Parque Nacional Waraira Repano',
    city: 'Caracas',
    country: 'Venezuela',
    capacity: 300,
    type: 'outdoor',
    status: Status.ACCEPTED,
    description: 'Zona de entrenamiento funcional al aire libre con guias certificados.',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
    mapUrl: 'https://maps.google.com/?q=Sabas+Nieves+Caracas',
  },
  {
    key: 'place-santa-rosalia-lab',
    ownerKey: 'admin-juan',
    name: 'Laboratorio Creativo Santa Rosalia',
    direction: 'Quinta Creativa, Avenida Sur 3, Santa Rosalia',
    city: 'Caracas',
    country: 'Venezuela',
    capacity: 140,
    type: 'studio-multimedia',
    status: Status.PENDING,
    description: 'Estudio para produccion audiovisual, talleres de podcast y fotografia.',
    image: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
    mapUrl: 'https://maps.google.com/?q=Santa+Rosalia+Caracas',
  },
];
