import { TicketSeed } from './types';

export const tickets: TicketSeed[] = [
  {
    key: 'ticket-dev-general',
    eventKey: 'event-dev-meetup',
    type: 'General',
    price: 0,
    quantity: 120,
    description: 'Acceso general con bebidas no alcoholicas incluidas.',
  },
  {
    key: 'ticket-dev-founder',
    eventKey: 'event-dev-meetup',
    type: 'Founder Pass',
    price: 25,
    quantity: 40,
    description: 'Incluye mesa redonda privada con speakers y kit de bienvenida.',
  },
  {
    key: 'ticket-ruta-general',
    eventKey: 'event-ruta-gastronomica',
    type: 'General',
    price: 18,
    quantity: 80,
    description: 'Degustacion de 6 estaciones y guia especializada.',
  },
  {
    key: 'ticket-rooftop-general',
    eventKey: 'event-rooftop-electronica',
    type: 'Dancefloor',
    price: 45,
    quantity: 250,
    description: 'Incluye acceso a pista principal y dos cocteles de cortesia.',
  },
  {
    key: 'ticket-rooftop-vip',
    eventKey: 'event-rooftop-electronica',
    type: 'Sky Lounge',
    price: 90,
    quantity: 90,
    description: 'Mesa reservada, botella premium y fast track.',
  },
  {
    key: 'ticket-teresa-platea',
    eventKey: 'event-teresa-sinf',
    type: 'Platea',
    price: 55,
    quantity: 260,
    description: 'Butacas centrales platea con programa coleccionable.',
  },
  {
    key: 'ticket-teresa-balcon',
    eventKey: 'event-teresa-sinf',
    type: 'Balcon',
    price: 32,
    quantity: 180,
    description: 'Ubicaciones balcon con vista panoramica.',
  },
  {
    key: 'ticket-waraira-team',
    eventKey: 'event-waraira-sunrise',
    type: 'Team Pack',
    price: 28,
    quantity: 40,
    description: 'Entrada para dos personas con hidratacion y fotografia.',
  },
  {
    key: 'ticket-waraira-solo',
    eventKey: 'event-waraira-sunrise',
    type: 'Solo',
    price: 16,
    quantity: 70,
    description: 'Incluye acceso al entrenamiento y smoothie recovery.',
  },
  {
    key: 'ticket-podcast-pro',
    eventKey: 'event-podcast-makers',
    type: 'Pro',
    price: 40,
    quantity: 35,
    description: 'Incluye asesoria personalizada y uso de estudio por 1 hora extra.',
  },
  {
    key: 'ticket-podcast-community',
    eventKey: 'event-podcast-makers',
    type: 'Community',
    price: 25,
    quantity: 45,
    description: 'Acceso al workshop y plantilla de plan de contenido.',
  },
];
