import { Gender, Membership, ROLE } from '@prisma/client';

import { UserSeed } from './types';

export const users: UserSeed[] = [
  {
    key: 'admin-juan',
    name: 'Juan Sebastian',
    lastName: 'Rivas',
    email: 'juan.admin@caracasclub.com',
    password: 'AdminCaracas24',
    birthDate: new Date('1988-04-15'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.ADMIN,
    membership: Membership.VIP,
    documentId: 14892345,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518',
  },
  {
    key: 'market-sofia',
    name: 'Sofia',
    lastName: 'Casanova',
    email: 'sofia.casanova@avstreetfood.com',
    password: 'MarketSofia24',
    birthDate: new Date('1991-11-02'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.WOMAN,
    role: ROLE.MARKET,
    membership: Membership.VIP,
    documentId: 16903456,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
  },
  {
    key: 'market-alejandro',
    name: 'Alejandro',
    lastName: 'Quintero',
    email: 'alejandro.quintero@nocturna.ve',
    password: 'MarketAlejandro24',
    birthDate: new Date('1987-05-09'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.MARKET,
    membership: Membership.VIP,
    documentId: 14789632,
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce',
  },
  {
    key: 'client-daniela',
    name: 'Daniela',
    lastName: 'Salazar',
    email: 'daniela.salazar@correo.com',
    password: 'ClientDan24',
    birthDate: new Date('1995-02-20'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.WOMAN,
    role: ROLE.CLIENT,
    membership: Membership.VIP,
    documentId: 19234561,
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
  },
  {
    key: 'client-gabriel',
    name: 'Gabriel',
    lastName: 'Acosta',
    email: 'gabriel.acosta@correo.com',
    password: 'ClientGab24',
    birthDate: new Date('1993-08-14'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 20123456,
    image: 'https://images.unsplash.com/photo-1504593811423-6dd665756598',
  },
  {
    key: 'client-luisa',
    name: 'Luisa',
    lastName: 'Villalobos',
    email: 'luisa.villalobos@correo.com',
    password: 'ClientLui24',
    birthDate: new Date('1997-04-30'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.WOMAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 21129834,
    image: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  },
  {
    key: 'client-ricardo',
    name: 'Ricardo',
    lastName: 'Mendoza',
    email: 'ricardo.mendoza@correo.com',
    password: 'ClientRic24',
    birthDate: new Date('1990-01-19'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.VIP,
    documentId: 19876543,
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce',
  },
  {
    key: 'client-natalia',
    name: 'Natalia',
    lastName: 'Perdomo',
    email: 'natalia.perdomo@correo.com',
    password: 'ClientNat24',
    birthDate: new Date('1999-06-04'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.WOMAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 22567819,
    image: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4',
  },
  {
    key: 'client-sergio',
    name: 'Sergio',
    lastName: 'Aranguren',
    email: 'sergio.aranguren@correo.com',
    password: 'ClientSer24',
    birthDate: new Date('1989-09-25'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 17654321,
    image: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39',
  },
  {
    key: 'client-elisabeth',
    name: 'Elisabeth',
    lastName: 'Figueroa',
    email: 'elisabeth.figueroa@correo.com',
    password: 'ClientEli24',
    birthDate: new Date('1996-12-12'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.WOMAN,
    role: ROLE.CLIENT,
    membership: Membership.VIP,
    documentId: 23890756,
    image: 'https://images.unsplash.com/photo-1544723795-4325378412f5',
  },
  {
    key: 'client-mikele-salomon',
    name: 'Mikele',
    lastName: 'Salomon',
    email: 'salomonmig@gmail.com',
    password: 'prueba1234',
    birthDate: new Date('1994-07-18'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 24578123,
  },
  {
    key: 'client-eliezer-cario',
    name: 'Eliezer',
    lastName: 'Cario',
    email: 'eliezermanuelcr@gmail.com',
    password: 'prueba1234',
    birthDate: new Date('1993-11-05'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 24689234,
  },
  {
    key: 'client-juan-andres-cuevas',
    name: 'Juan Andres',
    lastName: 'Cuevas',
    email: 'juanandrescuevas14@gmail.com',
    password: 'prueba1234',
    birthDate: new Date('1992-03-22'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 24750345,
  },
  {
    key: 'client-gabriel-cuevas',
    name: 'Gabriel',
    lastName: 'Cuevas',
    email: 'gabriel300905@gmail.com',
    password: 'prueba1234',
    birthDate: new Date('1990-09-05'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 24815678,
  },
  {
    key: 'client-jhonaiker-blanco',
    name: 'Jhonaiker',
    lastName: 'Blanco',
    email: 'blancojhonaiker@gmail.com',
    password: 'prueba1234',
    birthDate: new Date('1995-01-27'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 24893412,
  },
  {
    key: 'client-miguel-salomon',
    name: 'Miguel',
    lastName: 'Salomon',
    email: 'mdsalomon1006@gmail.com',
    password: 'prueba1234',
    birthDate: new Date('1991-10-06'),
    city: 'Caracas',
    country: 'Venezuela',
    gender: Gender.MAN,
    role: ROLE.CLIENT,
    membership: Membership.NORMAL,
    documentId: 24962157,
  },
];
